### ISSUE TITLE
Change the username from `MadhavBahlMD` to `MadhavBahl`

### ISSUE THREAD

**Issue by MadhavBahl** [CodeToExpress/dailycodebase#369]
I have changed my username from `MadhavBahlMD` to `MadhavBahl`

Creating an issue to update the username at all places, 

assigning this issue to myself 

But I won't be taking this up anytime soon, So if anyone (beginner in open source) wants to take this documentation issue as a first time contribution, you can utilize this issue 😃

**Comment by evansusu** [comment]
Hi I'd like to take this issue as a first timer, what do I need to do?

**Comment by mihirg008** [comment]
Hi! Would Like to work on this.

**Comment by MadhavBahl** [comment]
Hi @evansusu , @mihirg008  already opened a PR for this one, let's go with that

**Comment by DanBN95** [comment]
Hi! I would like to work on this. Thank you

**Comment by khanyasar022** [comment]
hey, I would really love to work on this to learn something as i'm a beginner.
