### ISSUE TITLE
Fix day4 README

### ISSUE THREAD

**Issue by Razdeep** [CodeToExpress/dailycodebase#53]
The README markdown has been broken with the last commit.

**Comment by MadhavBahlMD** [comment]
I will fix it 👍 

Thanks for informing

**Comment by MadhavBahlMD** [comment]
Made a commit. please check it once again

**Comment by Razdeep** [comment]
Fixed a markdown problem. Looks good now.

**Comment by MadhavBahlMD** [comment]
Great 🌟 

Closing this issue
