### ISSUE TITLE
Broken README in Day1, 2 & 3

### ISSUE THREAD

**Issue by ashwek** [CodeToExpress/dailycodebase#69]
Image **ques.png** is not loading in `Day1`, `Day2` & `Day3` _README.md_ because the images are added in different folders.
_ques.png_ is added in **d**ay1 but used in **D**ay1

**Comment by MadhavBahlMD** [comment]
I'll fix it 👍

**Comment by MadhavBahlMD** [comment]
Fixed 😃 

Thanks
